locustfile = ./scenarios/baseline/baseline_scenario.py
spawn-rate = 5
run-time = 15m
headless = false
users = 50
html = ./reports/baseline/html_report.html
csv = baseline_scenario
csv-full-history = true